
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 06 18:39:17 CEST 2009
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 23;
  public static final int DIVEQ = 21;
  public static final int GTEQ = 13;
  public static final int MULT = 20;
  public static final int CHAR = 43;
  public static final int LTEQ = 11;
  public static final int INTEGER = 38;
  public static final int LPAREN = 29;
  public static final int INT = 39;
  public static final int MINUS = 28;
  public static final int CHARACTER = 42;
  public static final int RPAREN = 30;
  public static final int OROR = 18;
  public static final int SEMICOLON = 35;
  public static final int NOT = 10;
  public static final int LT = 12;
  public static final int COMMA = 36;
  public static final int DIV = 22;
  public static final int ANDAND = 17;
  public static final int PLUSEQ = 24;
  public static final int MINUSEQ = 27;
  public static final int PLUS = 25;
  public static final int IF = 5;
  public static final int ID = 37;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 26;
  public static final int RETURN = 8;
  public static final int error = 1;
  public static final int EQEQ = 15;
  public static final int MULTEQ = 19;
  public static final int NUMBERF = 40;
  public static final int VOID = 4;
  public static final int EQ = 16;
  public static final int PRINTF = 2;
  public static final int LBRACK = 33;
  public static final int LBRACE = 31;
  public static final int ELSE = 6;
  public static final int RBRACK = 34;
  public static final int WHILE = 7;
  public static final int FLOAT = 41;
  public static final int RBRACE = 32;
  public static final int STRING = 44;
  public static final int GETS = 3;
  public static final int GT = 14;
  public static final int NOTEQ = 9;
}

